### ISSUE TITLE
Visits Metric Not Returning

### ISSUE THREAD

**Issue by kelpisland** [BCDevExchange/BCDevExchange-app#146] opened 2015-09-16 16:56 UTC
After the build this morning the visits metric isn't returning. See Below:
![screen shot 2015-09-16 at 9 43 32 am](https://cloud.githubusercontent.com/assets/9368818/9911857/0ce5469e-5c59-11e5-9182-3c04fca8ec5e.png)

**Comment by f-w** [comment] 2015-09-16 17:04
This doesn't seem to caused by code. @ll911 changed directory structure yesterday when implementing ci. However google analytics config in local.json has hard coded file name.

**Comment by ll911** [comment] 2015-09-16 18:12
fixed with local.json update svn Rev: 96

**Closed** 2015-09-16 18:12 UTC
Labels: bug
