### ISSUE TITLE
Account information not displaying

### ISSUE THREAD

**Issue by AlexWhiteIncorporated** [BCDevExchange/BCDevExchange-app#22] opened 2015-03-17 22:30 UTC
1. Navigate to Sign Up
2. Activate Sign Up button
3. System displays Accounts page
4. Press the browser back button
5. Press Sign Up button again

Account details do not display. Page does not seem to recognize log in attempt - Link your GitHub account button is enabled (normally disabled post sign up / log in)

**Comment by GregTurner** [comment] 2015-03-20 17:36
duplicate of #32

**Closed by GregTurner** 2015-03-20 17:36 UTC
